export const OPERATION_LABELS: Record<string, string> = {
  PERSON_READ: 'جلب معلوملت الزبائن',
  PERSON_CREATE: 'اضافة  زبون جديد ',
  PERSON_DELETE: 'حذف زبون ',
  CREATE_PAYMENT_PLAN: 'اضافة خطة دفع ',
  GET_PAYMENT_PLAN: 'جلب معلومات خطة الدفع ',
  UPDATE_PAYMENT_PLAN: 'تحديث خطة الدفع ',
  UPDATE_INSTALLMENT: 'تحديث الاقساط',
  GET_INSTALLMENT: 'جلب الاقساط',
  GET_NOTIFICATTIONS: 'جلب الاشعارات',
  GET_DASHBOARD: 'جلب لوحة القيادة',
  ADD_CONTRSCT: 'اضافة عقد',
  GET_CONTRACT: 'جلب العقود',
  DELETE_CONTRACT: 'حذف عقد',
  CREATE_CAR: 'اضافة سيارة ',
  UPDATE_CAR: 'تحديث سيارة ',
  DELETE_CAR: 'حذف سيارة',
  GET_CAR: 'جلب معلومات السياراة',
  CREATE_BRANCH: 'اضافة فرع ',
  GET_BRANCH: 'جلب الفروع ',
  PERSON_UPDATE: 'تعديل شخص',
  GET_USER_INFO: 'جلب معلومات مستخدم داخل الشركة',
};
